name: PR Validation

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint check
        run: npm run check

      - name: Run TypeScript build check
        run: npm run build

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            dist/
            node_modules/
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

  code-quality:
    runs-on: ubuntu-latest
    needs: lint-and-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for unused dependencies
        run: |
          npx depcheck --ignores="@types/*,eslint-*,@eslint/*,@vitejs/*,@commitlint/*,husky,jiti,postcss,autoprefixer"

      - name: Audit dependencies for vulnerabilities
        run: npm audit --audit-level moderate

  pr-info:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: PR Info
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            console.log(`PR Title: ${pullRequest.title}`);
            console.log(`PR Author: ${pullRequest.user.login}`);
            console.log(`Base Branch: ${pullRequest.base.ref}`);
            console.log(`Head Branch: ${pullRequest.head.ref}`);
            console.log(`Files Changed: ${pullRequest.changed_files}`);
            console.log(`Additions: ${pullRequest.additions}`);
            console.log(`Deletions: ${pullRequest.deletions}`);
